Removed Exception for unknown exchange type
Custom exchange types (e.g. rabbitmq_consistent_hash_exchange) are not supported because of this exception.
After removing this code on unknown exchange types, there will be an other meaningful exception.
Fatal error: Uncaught exception 'AMQPExchangeException' with message 'Server connection error: 503, message: COMMAND_INVALID - unknown exchange type 'unknown_exchange'